name: test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Install bundler2
      run: gem install bundler

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3

    - name: Run rspec
      run: bundle exec rspec
